#!/bin/bash 
#
# chkconfig: 35 91 11
# description: API Nagios Detect 
#

# Get function from functions library
#. /etc/init.d/functions
api_nagios_detect_proc=`ps -efa | grep python | grep ./nagios_watch_changes.py | awk  '{if ($9 =="./nagios_watch_changes.py") print $2'}`
# Start the service API Nagios Service Detect

start() {
	if [ ! -z $api_nagios_detect_proc ]; then
                echo "API Nagios Detect Service is Running with Process: $api_nagios_detect_proc"
                exit 0
        else
        echo "Starting API Nagios Detect Service: "
       	cd /MONITORIZACION/uti/nagios_apicreate/ ; nohup ./nagios_watch_changes.py > nohup.out &
        ### Create the lock file ###
	touch  /var/lock/subsys/api_nagios_detect
        echo "API Nagios Service Detect startup with process: $api_nagios_detect_proc"
	api_nagios_detect_proc=`ps -efa | grep python | grep ./nagios_watch_changes.py | awk  '{if ($9 =="./nagios_watch_changes.py") print $2'}`
        echo $api_nagios_detect_proc >  /var/run/nagios_api_create.pid
	echo
	fi
}

# Restart the service FOO
stop() {
        echo  "Stopping API Nagios Detect Service:" 
        kill -9  $api_nagios_detect_proc
        ### Now, delete the lock file ###
        rm -f /var/lock/subsys/api_nagios_detect
        echo
}


status()
	if [ ! -z $api_nagios_detect_proc ]; then 
		echo "API Nagios Detect Service is Running with Process: $api_nagios_detect_proc"
		exit 0 
	else  
		echo "API Nagios Service Detect is ShutDown"
		exit 2
	fi

### main logic ###
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status
        ;;
  restart|reload|condrestart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac

exit 0

